- name: Install Chrony package
  dnf:
    name: chrony
    state: present

- name: Configure Chrony with custom template
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf

- name: Start and enable Chrony service
  systemd:
    name: chronyd
    state: started
    enabled: true

- name: Ensure Chrony is synchronized
  command: chronyc sources
  register: chronyc_output

- name: Debug Chrony synchronization status
  debug:
    msg: "{{ chronyc_output.stdout_lines }}"
