- name: Ensure iptables is installed
  package:
    name: iptables
    state: present

- name: Allow SSH traffic
  command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT

- name: Allow HTTP traffic
  command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

- name: Allow HTTPS traffic
  command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT

- name: Drop all other incoming traffic
  command: iptables -A INPUT -j DROP
  notify:
    - Save iptables rules
